In [ ]:
! pip install torch

In [2]:
import numpy as np
import torch

Tensor -> n차원의 행렬 형태로 표현되는 데이터(자료형??)</br>
(스칼라 텐서 : 0차원, 벡터 텐서 : 1차원 텐서, 매트릭스 텐서 : 2차원 텐서)</br>
(여기서 n차원 = n Rank로 표현한다.)</br>
ex) 가로 세로 100px인 컬러 사진 이미지 1장은? : [3, 100, 100]의 3차원 텐서 자료형이 될 수 있다.</br>
이때, 이 사진 개수가 5장이다 -> [5, 3, 100, 100]

1. 텐서 자료형 만들기 -> torch.tensor()

In [3]:
torch.tensor(5) #스칼라 텐서 5를 만듬

torch.tensor([1, 2, 4, 5, 6]) #1차원 텐서 (벡터)

torch.tensor([[13, 45], [2, 3]]) #2차원 텐서 (메트릭스)

tensor([[13, 45],
        [ 2,  3]])

In [3]:
tmp_list = [1, 2, 3, 4, 5]
torch.tensor(tmp_list) #매개변수로 리스트 입력 가능
#텐서 자료형에 입력 가능한 매개변수 자료형 : list, set, numpy array

torch_set = (1, 2, 3, 4,5)
torch.tensor(torch_set)

torch_np_array = np.array(tmp_list)
torch.tensor(torch_np_array)


tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [6]:
#torch.ones()  -> element가 1인 tensor을 만들어주는 명령어

a = torch.ones([3, 3]) #3 x 3매트릭스 tensor을 만들어달라(이때 각 요소값은 1)

b = torch.ones([3,3,3])

print(a)
print(b)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


In [8]:
#torch.zeros()는 ones()랑 똑같은데 채우는 요소값이 0인거

torch.zeros([4,2])

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [9]:
#torch.arange()는 start, end, step 3가지 매개변수 갖으며, list range랑 같다 보면됨

torch.arange(1, 14)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [10]:
#torch.rand()는 0~1사이의 난수 요소를 생성해서 차원값에 맞게 생성

torch.rand([2,3])

tensor([[0.2805, 0.8273, 0.0197],
        [0.5078, 0.5821, 0.4135]])

In [18]:
#torch.xxx_likes() -> 이전에 생성한 텐서와 같은 모양의 tensor 자료형을 만드는데
#이 생성된 tensor자료형의 원소값(element)는 xxx에 맞게 채움
#xxx는 once, zeros 두개가 있는 듯

a = torch.zeros([3,4,5])
c = torch.ones_like(a)

b = torch.rand([2,3])
d = torch.zeros_like(b)

print(a, c)
print(b, d)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]) tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])
tensor([[0.8803, 0.6726, 0.6485],
        [0.1577, 0.7233, 0.2820]]) tensor([[0., 0., 0.],
        [0., 0., 0.]])


2. Attribute : Shape, dtype, device</br>
이거는 텐서의 모양, 데이터타입, GPU/CPU로 연산중인지 확인하는거

In [21]:
a = torch.tensor([1,2,3,4,5])
print(a.shape)

b = torch.ones([3,4,5,5])
print(b.shape)

torch.Size([5])
torch.Size([3, 4, 5, 5])


In [22]:
#Tensor.dtype는 텐서의 타입을 보여줌(int, float, double인지)
print(a.dtype, b.dtype)

torch.int64 torch.float32


In [23]:
#데이터 타입을 다른 형식으로 만드는 방법
#long, int, double, float를 주로 사용함

float_tensor = torch.ones(1, dtype=torch.float)
double_tensor = torch.ones(1, dtype=torch.double)
complex_float_tensor = torch.ones(1, dtype=torch.complex64)
complex_double_tensor = torch.ones(1, dtype=torch.complex128)
int_tensor = torch.ones(1, dtype=torch.int)
long_tensor = torch.ones(1, dtype=torch.long)
uint_tensor = torch.ones(1, dtype=torch.uint8)
bool_tensor = torch.ones(1, dtype=torch.bool)



In [7]:
#tensor.device는 쿠다인지 CPU인지 확인하는거

a = torch.tensor([1,2,3,4,5])
print(a. device)

#GPU사용 가능 환경인지 확인하자
print(torch.cuda.is_available())


#사용환경이 available이 된다음 GPU사용환경을 확인하자.
torch.cuda.get_device_name(device=0)

torch.cuda.device_count()


#이거는 텐서 자료형을 GPU에 할당하는 방법
a_cuda = torch.tensor([1,23,4,5]).cuda()
b_cuda = torch.tensor([1,2,3,4,5]).to('cuda')

cpu
True


In [26]:
! nvcc --V

'nvcc'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.


3. Tensor Aggregation : Element-wise 연산 -> min, max, mean

In [29]:
#element-wise -> 탠서 자료형이 따지고 보면 행렬이니 행렬연산

a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])

print(a, b)

print(a+b, a-b, a*b,a/b)
#이렇게 산술연산으로 행렬 연산이 가능하다.

print(a.add(b), a.sub(b), a.mul(b), a.div(b))

tensor([[1, 2],
        [3, 4]]) tensor([[5, 6],
        [7, 8]])
tensor([[ 6,  8],
        [10, 12]]) tensor([[-4, -4],
        [-4, -4]]) tensor([[ 5, 12],
        [21, 32]]) tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[ 6,  8],
        [10, 12]]) tensor([[-4, -4],
        [-4, -4]]) tensor([[ 5, 12],
        [21, 32]]) tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [31]:
#inplace 연산 -> 연산결과를 반환하면서 자기 자신의 데이터를 고침
#연산자 함수 뒤에 '_'를 붙인다
#res = a+b인데 _를 붙이면 a = a+b 이게 되버린다는 뜻...

print(a.add(b))
print(a)

print(a.add_(b))
print(a)

tensor([[11, 14],
        [17, 20]])
tensor([[ 6,  8],
        [10, 12]])
tensor([[11, 14],
        [17, 20]])
tensor([[11, 14],
        [17, 20]])


In [32]:
#Tensor.min() -> 텐서 자료형의 각 원소 값 중 가장 작은 값, 위치 반환

a = torch.tensor([[1,2],[3,4]])
print(a)

print(a.shape)
print(a.min())
print(a.min(dim=0))
print(a.min(dim=1))


tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
tensor(1)
torch.return_types.min(
values=tensor([1, 2]),
indices=tensor([0, 0]))
torch.return_types.min(
values=tensor([1, 3]),
indices=tensor([0, 0]))


In [35]:
#tensor.max() 이거는 가장 큰 값을 반환해줌

b = torch.tensor([[2,3,4],[2,4,5]])

print(b)
print(b.shape)
print(b.max())

print(b.max(dim=0))
print(b.max(dim=1))

tensor([[2., 3., 4.],
        [2., 4., 5.]])
torch.Size([2, 3])
tensor(5.)
torch.return_types.max(
values=tensor([2., 4., 5.]),
indices=tensor([0, 1, 1]))
torch.return_types.max(
values=tensor([4., 5.]),
indices=tensor([2, 2]))


In [36]:
# tensor.mean() -> 요소의 전체 평균 혹은 argument에 지정한 차원의 내 요소의 전제평균

b = torch.tensor([[2,3,4],[2,4,5]], dtype=torch.float)

print(b)

print(b.mean())

print(b.mean(dim=0))
print(b.mean(dim=1))

tensor([[2., 3., 4.],
        [2., 4., 5.]])
tensor(3.3333)
tensor([2.0000, 3.5000, 4.5000])
tensor([3.0000, 3.6667])


4. Index -> numpy, pandas의 인덱싱과 유사함

In [12]:
a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

print(a.shape)

print(a[1])

print(a[1][2])

torch.Size([3, 3])
tensor([4, 5, 6])
tensor(6)


In [14]:
b = torch.rand([3,3,3])
print(b)
print(b[0:2])

tensor([[[0.3612, 0.1982, 0.6672],
         [0.8384, 0.3059, 0.8934],
         [0.0416, 0.7388, 0.5850]],

        [[0.7501, 0.0291, 0.5800],
         [0.8967, 0.9097, 0.8916],
         [0.8819, 0.1856, 0.7407]],

        [[0.5438, 0.6362, 0.4709],
         [0.7654, 0.1145, 0.3741],
         [0.5163, 0.7952, 0.1378]]])
tensor([[[0.3612, 0.1982, 0.6672],
         [0.8384, 0.3059, 0.8934],
         [0.0416, 0.7388, 0.5850]],

        [[0.7501, 0.0291, 0.5800],
         [0.8967, 0.9097, 0.8916],
         [0.8819, 0.1856, 0.7407]]])


5. Shaping Opeation : reshape, squeeze/unsqueeze, stack, cat </br>
텐서 자료형의 차원이나 모양을 바꾸는것

In [24]:
#tensor.reshape() -> 모양 변경(차원의 길이 변경)
#만약 차원의 모든 곱 값이 x * y * z = k 일 때
#이 k를 만들 수 있는 다른 공약수로 reshape가 가능하다.

a = torch.tensor([[1,2,3,4],[5,6,7,8]])

print(a.shape)

print(a.reshape([4,2]))

print(a.reshape([2,2,2]))

print(a.reshape([1,2,4]))

print(a.reshape([-1, 8]))
print(a.reshape([-1, 8]).shape)

torch.Size([2, 4])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]]])
tensor([[1, 2, 3, 4, 5, 6, 7, 8]])
torch.Size([1, 8])


In [25]:
#Tensor.squeeze() -> 차원의 값이 1인 차원을 제거한다
#차원의 값이 1인건 따지고 보면 원소가 없이 []이것만 붙은거니까 없애준다는 거임
#차원이 꽤 높은 고차원 tensor자료형을 정사영 한다는 뜻이 된다 보면 됨

a = torch.rand([3,1,3])

print(a)
print(a.shape)
print(a.squeeze())
print(a.squeeze().shape)

tensor([[[0.1961, 0.0294, 0.6034]],

        [[0.4980, 0.8593, 0.3893]],

        [[0.2112, 0.2826, 0.9144]]])
torch.Size([3, 1, 3])
tensor([[0.1961, 0.0294, 0.6034],
        [0.4980, 0.8593, 0.3893],
        [0.2112, 0.2826, 0.9144]])
torch.Size([3, 3])


In [ ]:
#Tensor.unsqueeze() 이거는 반대로 차원을 늘리는것
#Tensor.squeeze()와 같게 argument로 dim을 쓸 수 있는데 이거로
#늘리거나 줄이는 차원을 조정할 수 있음

b = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [33]:
#torch.cat(), torch.stack() -> 두개의 tensor자료형을 합치는 방식

a = torch.rand(5, 24, 50) #M, N, K
b = torch.rand(5, 24, 50) #M, N, K

res1 = torch.cat([a,b], dim = 0) # -> 이거는 첫번재 차원값 M을 M+M, N, K하는거

res2 = torch.cat([a,b], dim=1) # 이거는 N값을 N+N
res3 = torch.cat([a,b], dim=2) 

print(res1.shape)
print(res2.shape)
print(res3.shape)


c = torch.rand(5,24,50)
d = torch.rand(2,24,50)
#위 경우에는 cat할 시 dim=0만 가능하다 -> 이유는 M+M 일때 N, K는 같은 값이어야함
#N+N하려면, M, K가 각각 같은 값이어야 하는데 M이 다름

res_1 = torch.cat([a,b], dim=0)
print(res_1.shape)


e = torch.rand(3, 24, 50)
f = torch.rand(3, 24, 50)

res_1_1 = torch.stack([a, b], dim=0)
res_1_2 = torch.stack([a, b], dim=1)
res_1_3 = torch.stack([a, b], dim=2)

print()
print(res_1_1.shape)
print(res_1_2.shape)
print(res_1_3.shape)


aa = torch.rand(3, 4)
bb = torch.rand(3, 4)

res_2_1 = torch.stack([aa,bb], dim=0)
res_2_2 = torch.stack([aa,bb], dim=1)

print()
print(res_2_1.shape)
print(res_2_2.shape)

torch.Size([10, 24, 50])
torch.Size([5, 48, 50])
torch.Size([5, 24, 100])
torch.Size([10, 24, 50])

torch.Size([2, 5, 24, 50])
torch.Size([5, 2, 24, 50])
torch.Size([5, 24, 2, 50])

torch.Size([2, 3, 4])
torch.Size([3, 2, 4])
