In [1]:
import torch
import numpy as np

1. Matrix Multiplication

In [2]:
m1 = torch.tensor([[1,2,3,],[4,5,6],[7,8,9]])
m2 = torch.tensor([[1,2,3,],[4,5,6],[7,8,9]])

print(m1.shape, m2.shape)

res1 = m1.mul(m2) #행렬 원소곱
res2 = m1.matmul(m2) #행렬 곱
#행렬곱의 경우 m1@m2로 표현 가능하다

print(res1, res1.shape)
print(res2, res2.shape)

torch.Size([3, 3]) torch.Size([3, 3])
tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]]) torch.Size([3, 3])
tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]]) torch.Size([3, 3])


2. Linear Layer

In [8]:
# 4x2 텐서 자료형 곱하기
m1 = torch.tensor([[1,2,3,4,],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

m2 = torch.tensor([[1,2,3,4],[5,6,7,8]])

print(m1.shape, m2.shape)

m2 = m2.reshape(4,2)

res1 = m1@m2 #행렬곱

print(res1.shape, res1)

torch.Size([4, 4]) torch.Size([2, 4])
torch.Size([4, 2]) tensor([[ 50,  60],
        [114, 140],
        [178, 220],
        [242, 300]])


2. Linear Layer

In [13]:
# raw layer을 만들어보기

W = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) #weight matrix
B = torch.FloatTensor([1,1,1]) #bias matrix

print(W.shape, B.shape)

def linear_1(x, w, b):
    y = torch.matmul(x, w) + b
    return y

#이제 레이어 연산 y = f(x) +b 해보기

x1 = torch.FloatTensor([1,2,3,4])

x2 = torch.FloatTensor([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
#[batch_size, imput_dim]차원인 x2


layer_1 = linear_1(x1, W, B)
layer_2 = linear_1(x2, W, B) #batch처리 -> input(x)가 여러 레이어

print(layer_1, layer_1.shape)
print(layer_2, layer_2.shape)

torch.Size([4, 3]) torch.Size([3])
tensor([71., 81., 91.]) torch.Size([3])
tensor([[23., 27., 31.],
        [45., 53., 61.],
        [67., 79., 91.]]) torch.Size([3, 3])


nn.Module() -> 모든 뉴럴넷 모형의 기본이 됨
이거로 한번 실습해보기

In [5]:
import torch.nn as nn #각 레이어의 함수, 신경망 구조를 정의할 때 사용하는 클래스

In [20]:
class MyLinear_1(nn.Module): #클래스 상속 후 재정의 과정
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.input_dim = input_dim
        self.output_dim = output_dim

        self.W = torch.FloatTensor(input_dim, output_dim)
        self.b = torch.FloatTensor(output_dim)

        print(self.W, self.b) #W랑 b는 임의 원소값으로 채워지는 듯?

    def forward(self, x): #input을 받아서 레이어를 통과시키는 연산 함수
        y = torch.matmul(x, self.W) + self.b

        return y

In [31]:
x2 = torch.FloatTensor([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
#[batch_size = 3, imput_dim = 4]차원인 x2

linear2 = MyLinear_1(4,3)

y = linear2(x2)
print(y)

tensor([[-2.1367e+22,  2.3703e-38,  1.4013e-45],
        [-4.2734e+22,  2.3711e-38,  1.4013e-45],
        [-6.4100e+22,  2.3720e-38,  1.4013e-45],
        [ 1.3813e+03,  0.0000e+00,  1.5616e-05]]) tensor([3.5000e+01, 6.0240e-01, 2.3694e-38])
tensor([[-1.2820e+23,  6.0240e-01,  1.5616e-05],
        [-2.5640e+23,  6.0240e-01,  3.1233e-05],
        [-3.8460e+23,  6.0240e-01,  4.6849e-05]])


In [32]:
for i in linear2.parameters(): #클래스 내 파라미터를 확인하기 위한 for구문
    print(i) #일단 이거는 아무것도 출력이 되지 않는다 -> 이유는 아래에

In [34]:
class MyLinear_1(nn.Module): #클래스 상속 후 재정의 과정
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.input_dim = input_dim
        self.output_dim = output_dim

        self.W = torch.FloatTensor(input_dim, output_dim)
        self.b = torch.FloatTensor(output_dim)

    def forward(self, x): #input을 받아서 레이어를 통과시키는 연산 함수
        y = torch.matmul(x, self.W) + self.b

        return y
    

class MyLinear_2(nn.Module): #위 클래서에서 파라미터값 출력을 위한 부분이 추가된 클래스
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.input_dim = input_dim
        self.output_dim = output_dim

        self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
        self.b = nn.Parameter(torch.FloatTensor(output_dim))
        #네트워크로 설계할 때 학습이 필요한 W, B리고 알려줄 때 nn.Parameter

        print(self.W, self.b) #W랑 b는 임의 원소값으로 채워지는 듯?

    def forward(self, x): #input을 받아서 레이어를 통과시키는 연산 함수
        y = torch.matmul(x, self.W) + self.b

        return y

In [39]:
x2 = torch.FloatTensor([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
#[batch_size = 3, imput_dim = 4]차원인 x2

linear__1 = MyLinear_1(4,3)
linear__2 = MyLinear_2(4,3)

y_1 = linear__1(x2)
y_2 = linear__2(x2)
print(y_1, y_2)

Parameter containing:
tensor([[-3.5609e+21,  1.4349e-42,  1.0000e+00],
        [ 1.0000e+00,  2.0000e+00,  2.0000e+00],
        [ 2.0000e+00,  2.0000e+00,  3.0000e+00],
        [ 3.0000e+00,  3.0000e+00,  3.0000e+00]], requires_grad=True) Parameter containing:
tensor([0.0000e+00, 0.0000e+00, 2.3694e-38], requires_grad=True)
tensor([[  813.0000,  3744.0459,  1101.0000],
        [ 1626.0000,  7488.0918,  2202.0000],
        [ 2439.0000, 11232.1377,  3303.0000]]) tensor([[-3.5609e+21,  7.0000e+00,  9.0000e+00],
        [-7.1218e+21,  1.4000e+01,  1.8000e+01],
        [-1.0683e+22,  2.1000e+01,  2.7000e+01]], grad_fn=<AddBackward0>)


In [40]:
for i in linear__2.parameters(): #클래스 내 파라미터를 확인하기 위한 for구문
    print(i) #이 구문은 객체 linear__2의 내부에는 파라미터를 확인할 수 있도록 구문이 포함되어 있어서
             #중간의 파라미터값이 출력된다. (이 파라미터는 W, B 두개를 출력한다.)

Parameter containing:
tensor([[-3.5609e+21,  1.4349e-42,  1.0000e+00],
        [ 1.0000e+00,  2.0000e+00,  2.0000e+00],
        [ 2.0000e+00,  2.0000e+00,  3.0000e+00],
        [ 3.0000e+00,  3.0000e+00,  3.0000e+00]], requires_grad=True)
Parameter containing:
tensor([0.0000e+00, 0.0000e+00, 2.3694e-38], requires_grad=True)


nn.Linear() -> 위 과정을 한큐에 다 해준 클래스가 있는데 그게 nn.Linear()클래스임

In [46]:
x2 = torch.FloatTensor([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
#[batch_size = 3, imput_dim = 4]차원인 x2

linear_3 = nn.Linear(in_features=4, out_features=3)

y_3 = linear_3(x2)
print(y_3)
print(y_3.shape)

for p in linear_3.parameters():
    print(p)

print(linear_3.weight)
print(linear_3.bias)

#nn.Linear클래스는 일반적인 Fully Connected Layer이 다 설계되어 있는 클래스이다.

tensor([[-1.3835e-01, -6.6569e-01, -2.1696e-01],
        [-7.0271e-02, -1.7949e+00, -6.3066e-01],
        [-2.1936e-03, -2.9241e+00, -1.0444e+00]], grad_fn=<AddmmBackward0>)
torch.Size([3, 3])
Parameter containing:
tensor([[ 0.0188,  0.2644, -0.1616, -0.0535],
        [-0.2043, -0.2803, -0.2059, -0.4387],
        [-0.2059,  0.0281,  0.1152, -0.3511]], requires_grad=True)
Parameter containing:
tensor([-0.2064,  0.4635,  0.1967], requires_grad=True)
Parameter containing:
tensor([[ 0.0188,  0.2644, -0.1616, -0.0535],
        [-0.2043, -0.2803, -0.2059, -0.4387],
        [-0.2059,  0.0281,  0.1152, -0.3511]], requires_grad=True)
Parameter containing:
tensor([-0.2064,  0.4635,  0.1967], requires_grad=True)


In [47]:
#앞으로 Fullay Connected Layer 클래스의 설계는 아래와 같이 수행한다.

class MyLinear_3(nn.Module):

    def __init__(self, input_dim, output_dim):
        super.__init__()

        self.input_dim = input_dim
        self.output_dim = output_dim

        self.linear = nn.Linear(input_dim, output_dim)

        #self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
        #self.b = nn.Parameter(torch.FloatTensor(output_dim))
        #이 구문을 한번에 줄여준게 nn.Linear

    def forward(self, x):
        y = self.linear(x)

        return y

3. Activation Function </br>

활성화 함수에 관한 클래스가 따로 정의되어 있으니 그것을 import하면 된다</br>
활성화 함수는 relu, sigmod, tanh, leeky_relu, softmax등을 제공한다.

In [48]:
import torch.nn.functional as F #이게 활성화 함수를 제공하는 클래스(메서드함수군)
#해당 모듈에는 relu, sigmod, tanh, leeky_relu, softmax등이 포함되어 있음

In [49]:
#sigmod함수 예제
ex_sigmod = nn.Sigmoid()
input = torch.randn(2,3) #임의의 input 매트릭스 생성

output = ex_sigmod(input)
print(input, output)


tensor([[-0.8714,  0.2551,  0.1086],
        [-0.6204,  0.9494,  0.8667]]) tensor([[0.2950, 0.5634, 0.5271],
        [0.3497, 0.7210, 0.7041]])


In [51]:
#Relu함수 예제
ex_relu = nn.ReLU()
input = torch.randn(2,3) #임의의 input 매트릭스 생성

output = ex_relu(input)
print(input, output)

tensor([[ 0.1468,  1.4263, -0.1081],
        [-0.4708, -0.8003,  0.1103]]) tensor([[0.1468, 1.4263, 0.0000],
        [0.0000, 0.0000, 0.1103]])


In [58]:
#softmax함수 예제 -> 이 함수는 dim을 지정해줘야 한다.(왠만하면 dim=1을 쓰는 듯?)
ex_softmax = nn.Softmax(dim=1)
input = torch.randn(2,3) #임의의 input 매트릭스 생성

output = ex_softmax(input)
print(input, output)
print(output[0].sum()) #이 결과값은 1(dim값)이 나온다.
print(output[1].sum()) #이 결과값은 1(dim값)이 나온다.

tensor([[ 0.7705, -0.3533,  0.6807],
        [ 0.4040, -0.3561,  0.4958]]) tensor([[0.4466, 0.1452, 0.4082],
        [0.3901, 0.1824, 0.4275]])
tensor(1.0000)
tensor(1.)


4. loss Function 

In [61]:
import torch.nn as nn

In [60]:
#첫번째 MSE loss function -> 이 함수는 주로 Regression Task에 사용됨

mse_loss = nn.MSELoss()

pred = torch.randn(4, 10)
output = torch.rand(4, 10)
#임의의 두 매트릭스를 만든 뒤 이를 MSELoss가 객체화된 mse_loss로 차이를 알아봄

print(mse_loss(pred, output)) # 이 값이 작아지도록 하는게 training

tensor(1.5087)


nn.NLLLoss() : Navigative Log Likehood Loss </br>
이 함수는 Cross Entropy Loss 함수와 거의 동일하게 동작하는 Loss 함수라 보면 된다.</br>
좀더 정확하게는 Softmax + Log함수인 LogSoftmax 함수랑 같이 조합해서 CEL과 유사하게 동작하게 만듬</br>
이렇게 복잡하게 쓰는 이유 : NaN오류를 방지함

In [62]:
import torch.nn.functional as F 

In [67]:
#nn.NLLLoss() 함수 실습 -> 이거로 CEL을 구현해보자

m = nn.LogSoftmax(dim=1) #softmax함수의 NaN오류를 방지하는 함수

nll_loss = nn.NLLLoss()

pred = torch.randn([1,5], requires_grad=True)
#이것은 [0~1, 0~1, 0~1, 0~1, 0~1]임

output = torch.tensor([1]) #[0~4]사이의 클래스 라벨을 갖는다 설정하자
#이것의 으미가 [0, 1, 0, 0, 0]임
#즉 pred랑 output의 비교는 2번째 라벨이 된 확률은???을 물어보는 거임


print(torch.log(F.softmax(pred))) #이렇게 softmax를 바로 쓰면 NaN이 뜰 수 잇음
#m = nn.LogSoftmax(dim=1) == log(F.softmax(pred)) 같은 효과이나 좌변이 더 안정적

cal = m(pred) #이것이 torch.log(F.softmax(pred))와 같은 뜻임

print(nll_loss(cal, output)) #이렇게 써야 CEL을 구현한거



tensor(4.1149, grad_fn=<NllLossBackward0>)


In [68]:
#CEL과정 한번 더 실습

pred = torch.rand([3,5], requires_grad=True)
#위에거랑 다르게 batch size가 3개인거 (사진이 3장임)

output = torch.tensor([1,0,3])
#batch_size가 3이니, 각각 비교하는데 2번째, 1번째, 4번째 라벨이 정답(1)이라는 뜻


cal= m(pred)

print(nll_loss(cal, output))

tensor(1.5221, grad_fn=<NllLossBackward0>)


In [69]:
#위 과정이 복잡해 -> 한번에 다 구현한 메서드
#nn.CrossEntropyLoss() -> softmax, Nevigative Log Likelyhood 합본

ce_loss = nn.CrossEntropyLoss()

pred = torch.randn([1,5], requires_grad=True)
output = torch.tensor([3]) #4번째 레이블이 정답

ce_loss(pred, output)

tensor(1.7511, grad_fn=<NllLossBackward0>)

In [70]:
ce_loss = nn.CrossEntropyLoss()

pred = torch.randn([3,5], requires_grad=True)
output = torch.tensor([1,2,3]) #4번째 레이블이 정답

ce_loss(pred, output)

tensor(2.1128, grad_fn=<NllLossBackward0>)

In [71]:
ce_loss = nn.CrossEntropyLoss()

pred = torch.randn([3,5], requires_grad=True)
output = torch.randn([3,5]).softmax(dim=1) #이거는 라벨이 01000이 아니라 확률일 경우

ce_loss(pred, output)

tensor(1.8338, grad_fn=<DivBackward1>)

5. Loss의 최적화 -> GD, 백프로 파게이션</br>
이 최적화 방법론은 여러개 있으니 숙지할 것

In [74]:
#최적화 방법론까지 구현되어 있는 모델(클래스)를 만들어보자


class My_linear_5(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()

        self.input_dim = input_dim
        self.output_dim = output_dim

        self.linear = nn.Linear(input_dim, output_dim)

    def forward(self, x):
        y = self.linear(x)
        return y


model = My_linear_5(5, 3)

In [75]:
for p in model.parameters():
    print(p) #업데이트 대상이 되는 W, B가 어떻게 생겻는지 확인하기

Parameter containing:
tensor([[ 0.1141,  0.3681,  0.2716,  0.1136,  0.0049],
        [-0.0169,  0.2013, -0.0024, -0.0052, -0.1424],
        [ 0.1414,  0.0012,  0.1128, -0.0920, -0.0187]], requires_grad=True)
Parameter containing:
tensor([ 0.3347, -0.1129,  0.3575], requires_grad=True)


In [76]:
#SGD(Stocastic Gradient Descent)방법

sgd_optimizer = torch.optim.SGD(model.parameters(), lr =0.01, momentum=0.9)
#사용되는 argument 값은 의미를 확인하자

In [78]:
#ADAM 방법
adam_optimizer = torch.optim.Adam(model.parameters(), lr=0.001, betas=(0.9, 0.999))

위 GD방법론은 소개만 한거고 이제 본격적으로 학습에 사용하는 건 다음시간에